# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Crew(BaseModel):
    """
    Crew
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    active: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    company_name: Optional[StrictStr] = Field(default=None, alias="companyName")
    market_segment: Optional[StrictStr] = Field(default=None, alias="marketSegment")
    mobile_phone: Optional[StrictStr] = Field(default=None, alias="mobilePhone")
    street_address1: Optional[StrictStr] = Field(default=None, alias="streetAddress1")
    state_province: Optional[StrictStr] = Field(default=None, alias="stateProvince")
    sqft_per_day: Optional[StrictInt] = Field(default=None, alias="sqftPerDay")
    sqft_per_week: Optional[StrictInt] = Field(default=None, alias="sqftPerWeek")
    works_saturday: Optional[StrictBool] = Field(default=None, alias="worksSaturday")
    total_completed_installs: Optional[StrictInt] = Field(default=None, alias="totalCompletedInstalls")
    total_be_backs: Optional[StrictInt] = Field(default=None, alias="totalBeBacks")
    percent_of_be_backs_to_installs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="percentOfBeBacksToInstalls")
    move_appliances: Optional[StrictBool] = Field(default=None, alias="moveAppliances")
    rip_and_haul: Optional[StrictBool] = Field(default=None, alias="ripAndHaul")
    stairs: Optional[StrictBool] = None
    leveling: Optional[StrictBool] = None
    position_title: Optional[StrictStr] = Field(default=None, alias="positionTitle")
    glue_down_installation: Optional[StrictBool] = Field(default=None, alias="glueDownInstallation")
    date_certified: Optional[date] = Field(default=None, alias="dateCertified")
    project_capabilities: Optional[StrictStr] = Field(default=None, alias="projectCapabilities")
    plywood_and_subfloor_replacement: Optional[StrictBool] = Field(default=None, alias="plywoodAndSubfloorReplacement")
    baseboard_installation: Optional[StrictBool] = Field(default=None, alias="baseboardInstallation")
    star_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="starRating")
    attendance_violations: Optional[StrictInt] = Field(default=None, alias="attendanceViolations")
    stairs_per_day: Optional[StrictInt] = Field(default=None, alias="stairsPerDay")
    leveling_sqft: Optional[StrictInt] = Field(default=None, alias="levelingSqft")
    grade: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "name", "active", "email", "city", "companyName", "marketSegment", "mobilePhone", "streetAddress1", "stateProvince", "sqftPerDay", "sqftPerWeek", "worksSaturday", "totalCompletedInstalls", "totalBeBacks", "percentOfBeBacksToInstalls", "moveAppliances", "ripAndHaul", "stairs", "leveling", "positionTitle", "glueDownInstallation", "dateCertified", "projectCapabilities", "plywoodAndSubfloorReplacement", "baseboardInstallation", "starRating", "attendanceViolations", "stairsPerDay", "levelingSqft", "grade"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Crew from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Crew from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "active": obj.get("active"),
            "email": obj.get("email"),
            "city": obj.get("city"),
            "companyName": obj.get("companyName"),
            "marketSegment": obj.get("marketSegment"),
            "mobilePhone": obj.get("mobilePhone"),
            "streetAddress1": obj.get("streetAddress1"),
            "stateProvince": obj.get("stateProvince"),
            "sqftPerDay": obj.get("sqftPerDay"),
            "sqftPerWeek": obj.get("sqftPerWeek"),
            "worksSaturday": obj.get("worksSaturday"),
            "totalCompletedInstalls": obj.get("totalCompletedInstalls"),
            "totalBeBacks": obj.get("totalBeBacks"),
            "percentOfBeBacksToInstalls": obj.get("percentOfBeBacksToInstalls"),
            "moveAppliances": obj.get("moveAppliances"),
            "ripAndHaul": obj.get("ripAndHaul"),
            "stairs": obj.get("stairs"),
            "leveling": obj.get("leveling"),
            "positionTitle": obj.get("positionTitle"),
            "glueDownInstallation": obj.get("glueDownInstallation"),
            "dateCertified": obj.get("dateCertified"),
            "projectCapabilities": obj.get("projectCapabilities"),
            "plywoodAndSubfloorReplacement": obj.get("plywoodAndSubfloorReplacement"),
            "baseboardInstallation": obj.get("baseboardInstallation"),
            "starRating": obj.get("starRating"),
            "attendanceViolations": obj.get("attendanceViolations"),
            "stairsPerDay": obj.get("stairsPerDay"),
            "levelingSqft": obj.get("levelingSqft"),
            "grade": obj.get("grade")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


