# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class OrderItem(BaseModel):
    """
    OrderItem
    """ # noqa: E501
    id: Optional[StrictStr] = None
    appliance_count: Optional[StrictInt] = Field(default=None, alias="applianceCount")
    move_piano_pool_table: Optional[StrictStr] = Field(default=None, alias="movePianoPoolTable")
    multiple_layers: Optional[StrictInt] = Field(default=None, alias="multipleLayers")
    open_stair_count: Optional[StrictInt] = Field(default=None, alias="openStairCount")
    patch_leveling_required: Optional[StrictBool] = Field(default=None, alias="patchLevelingRequired")
    pedestal_sink_rr: Optional[StrictBool] = Field(default=None, alias="pedestalSinkRR")
    plywood_half_inch_sheets: Optional[StrictInt] = Field(default=None, alias="plywoodHalfInchSheets")
    plywood_quarter_inch_sheets: Optional[StrictInt] = Field(default=None, alias="plywoodQuarterInchSheets")
    plywood_three_quarter_inch_sheets: Optional[StrictInt] = Field(default=None, alias="plywoodThreeQuarterInchSheets")
    primer_type: Optional[StrictStr] = Field(default=None, alias="primerType")
    room_sq_ft: Optional[StrictInt] = Field(default=None, alias="roomSqFt")
    stair_count: Optional[StrictInt] = Field(default=None, alias="stairCount")
    toilet_rr: Optional[StrictBool] = Field(default=None, alias="toiletRR")
    true_self_leveling_required: Optional[StrictBool] = Field(default=None, alias="trueSelfLevelingRequired")
    vapor_barrier: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="vaporBarrier")
    sale: Optional[StrictStr] = None
    bifold_door_count: Optional[StrictInt] = Field(default=None, alias="bifoldDoorCount")
    build_up_leveling_required: Optional[StrictInt] = Field(default=None, alias="buildUpLevelingRequired")
    product_selected: Optional[StrictStr] = Field(default=None, alias="productSelected")
    bcid: Optional[StrictStr] = None
    molding_type: Optional[StrictStr] = Field(default=None, alias="moldingType")
    current_covering_type: Optional[StrictStr] = Field(default=None, alias="currentCoveringType")
    remove_current_surface: Optional[StrictBool] = Field(default=None, alias="removeCurrentSurface")
    available: Optional[StrictBool] = None
    product_name: Optional[StrictStr] = Field(default=None, alias="productName")
    product_grade: Optional[StrictStr] = Field(default=None, alias="productGrade")
    non_commissionable_item_total: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="nonCommissionableItemTotal")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "applianceCount", "movePianoPoolTable", "multipleLayers", "openStairCount", "patchLevelingRequired", "pedestalSinkRR", "plywoodHalfInchSheets", "plywoodQuarterInchSheets", "plywoodThreeQuarterInchSheets", "primerType", "roomSqFt", "stairCount", "toiletRR", "trueSelfLevelingRequired", "vaporBarrier", "sale", "bifoldDoorCount", "buildUpLevelingRequired", "productSelected", "bcid", "moldingType", "currentCoveringType", "removeCurrentSurface", "available", "productName", "productGrade", "nonCommissionableItemTotal"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "applianceCount": obj.get("applianceCount"),
            "movePianoPoolTable": obj.get("movePianoPoolTable"),
            "multipleLayers": obj.get("multipleLayers"),
            "openStairCount": obj.get("openStairCount"),
            "patchLevelingRequired": obj.get("patchLevelingRequired"),
            "pedestalSinkRR": obj.get("pedestalSinkRR"),
            "plywoodHalfInchSheets": obj.get("plywoodHalfInchSheets"),
            "plywoodQuarterInchSheets": obj.get("plywoodQuarterInchSheets"),
            "plywoodThreeQuarterInchSheets": obj.get("plywoodThreeQuarterInchSheets"),
            "primerType": obj.get("primerType"),
            "roomSqFt": obj.get("roomSqFt"),
            "stairCount": obj.get("stairCount"),
            "toiletRR": obj.get("toiletRR"),
            "trueSelfLevelingRequired": obj.get("trueSelfLevelingRequired"),
            "vaporBarrier": obj.get("vaporBarrier"),
            "sale": obj.get("sale"),
            "bifoldDoorCount": obj.get("bifoldDoorCount"),
            "buildUpLevelingRequired": obj.get("buildUpLevelingRequired"),
            "productSelected": obj.get("productSelected"),
            "bcid": obj.get("bcid"),
            "moldingType": obj.get("moldingType"),
            "currentCoveringType": obj.get("currentCoveringType"),
            "removeCurrentSurface": obj.get("removeCurrentSurface"),
            "available": obj.get("available"),
            "productName": obj.get("productName"),
            "productGrade": obj.get("productGrade"),
            "nonCommissionableItemTotal": obj.get("nonCommissionableItemTotal")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


