# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from fusion_refloor.models.crew import Crew
from fusion_refloor.models.flooring_color import FlooringColor
from fusion_refloor.models.inventory_item import InventoryItem
from fusion_refloor.models.order import Order
from fusion_refloor.models.order_item import OrderItem
from fusion_refloor.models.purchase_order_item import PurchaseOrderItem
from fusion_refloor.models.unavailable import Unavailable
from typing import Optional, Set
from typing_extensions import Self

class ScheduleModel(BaseModel):
    """
    ScheduleModel
    """ # noqa: E501
    order: Optional[Order] = None
    sale_order_items: Optional[List[OrderItem]] = Field(default=None, alias="saleOrderItems")
    inventory_items: Optional[List[InventoryItem]] = Field(default=None, alias="inventoryItems")
    purchase_order_items: Optional[List[PurchaseOrderItem]] = Field(default=None, alias="purchaseOrderItems")
    flooring_colors: Optional[List[FlooringColor]] = Field(default=None, alias="flooringColors")
    crews: Optional[List[Crew]] = None
    unavailability: Optional[List[Unavailable]] = None
    inventory_available: Optional[StrictBool] = Field(default=None, alias="inventoryAvailable")
    color_not_in_stock: Optional[StrictBool] = Field(default=None, alias="colorNotInStock")
    glue_down_order: Optional[StrictBool] = Field(default=None, alias="glueDownOrder")
    total_stairs: Optional[StrictInt] = Field(default=None, alias="totalStairs")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["order", "saleOrderItems", "inventoryItems", "purchaseOrderItems", "flooringColors", "crews", "unavailability", "inventoryAvailable", "colorNotInStock", "glueDownOrder", "totalStairs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScheduleModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sale_order_items (list)
        _items = []
        if self.sale_order_items:
            for _item in self.sale_order_items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['saleOrderItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in inventory_items (list)
        _items = []
        if self.inventory_items:
            for _item in self.inventory_items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['inventoryItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in purchase_order_items (list)
        _items = []
        if self.purchase_order_items:
            for _item in self.purchase_order_items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['purchaseOrderItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in flooring_colors (list)
        _items = []
        if self.flooring_colors:
            for _item in self.flooring_colors:
                if _item:
                    _items.append(_item.to_dict())
            _dict['flooringColors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in crews (list)
        _items = []
        if self.crews:
            for _item in self.crews:
                if _item:
                    _items.append(_item.to_dict())
            _dict['crews'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in unavailability (list)
        _items = []
        if self.unavailability:
            for _item in self.unavailability:
                if _item:
                    _items.append(_item.to_dict())
            _dict['unavailability'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScheduleModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "order": Order.from_dict(obj["order"]) if obj.get("order") is not None else None,
            "saleOrderItems": [OrderItem.from_dict(_item) for _item in obj["saleOrderItems"]] if obj.get("saleOrderItems") is not None else None,
            "inventoryItems": [InventoryItem.from_dict(_item) for _item in obj["inventoryItems"]] if obj.get("inventoryItems") is not None else None,
            "purchaseOrderItems": [PurchaseOrderItem.from_dict(_item) for _item in obj["purchaseOrderItems"]] if obj.get("purchaseOrderItems") is not None else None,
            "flooringColors": [FlooringColor.from_dict(_item) for _item in obj["flooringColors"]] if obj.get("flooringColors") is not None else None,
            "crews": [Crew.from_dict(_item) for _item in obj["crews"]] if obj.get("crews") is not None else None,
            "unavailability": [Unavailable.from_dict(_item) for _item in obj["unavailability"]] if obj.get("unavailability") is not None else None,
            "inventoryAvailable": obj.get("inventoryAvailable"),
            "colorNotInStock": obj.get("colorNotInStock"),
            "glueDownOrder": obj.get("glueDownOrder"),
            "totalStairs": obj.get("totalStairs")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


