# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from fusion_refloor.models.order_item import OrderItem
from typing import Optional, Set
from typing_extensions import Self

class ScheduleRequest(BaseModel):
    """
    ScheduleRequest
    """ # noqa: E501
    id: Optional[StrictStr] = None
    sale_id: Optional[StrictStr] = Field(default=None, alias="saleID")
    sold_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="soldPrice")
    total_sqft: Optional[StrictInt] = Field(default=None, alias="totalSqft")
    market_segment: Optional[StrictStr] = Field(default=None, alias="marketSegment")
    sale_order_items: Optional[List[OrderItem]] = Field(default=None, alias="saleOrderItems")
    proposed_start_date: Optional[date] = Field(default=None, alias="proposedStartDate")
    proposed_end_date: Optional[date] = Field(default=None, alias="proposedEndDate")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "saleID", "soldPrice", "totalSqft", "marketSegment", "saleOrderItems", "proposedStartDate", "proposedEndDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScheduleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sale_order_items (list)
        _items = []
        if self.sale_order_items:
            for _item in self.sale_order_items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['saleOrderItems'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScheduleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "saleID": obj.get("saleID"),
            "soldPrice": obj.get("soldPrice"),
            "totalSqft": obj.get("totalSqft"),
            "marketSegment": obj.get("marketSegment"),
            "saleOrderItems": [OrderItem.from_dict(_item) for _item in obj["saleOrderItems"]] if obj.get("saleOrderItems") is not None else None,
            "proposedStartDate": obj.get("proposedStartDate"),
            "proposedEndDate": obj.get("proposedEndDate")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


