# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from fusion_refloor.models.lender import Lender
from typing import Optional, Set
from typing_extensions import Self

class SoldOrder(BaseModel):
    """
    SoldOrder
    """ # noqa: E501
    id: Optional[StrictStr] = None
    market_segment: Optional[StrictStr] = Field(default=None, alias="marketSegment")
    sale_id: Optional[StrictStr] = Field(default=None, alias="saleID")
    total_sqft: Optional[StrictInt] = Field(default=None, alias="totalSqft")
    total_stairs: Optional[StrictInt] = Field(default=None, alias="totalStairs")
    glue_down_order: Optional[StrictBool] = Field(default=None, alias="glueDownOrder")
    additional_sale_comments: Optional[StrictStr] = Field(default=None, alias="additionalSaleComments")
    sold_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="soldPrice")
    payment_type: Optional[StrictStr] = Field(default=None, alias="paymentType")
    inventory_available: Optional[StrictBool] = Field(default=None, alias="inventoryAvailable")
    list_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="listPrice")
    loan_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="loanAmount")
    buydown: Optional[Union[StrictFloat, StrictInt]] = None
    rep_split: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="repSplit")
    sales_rep1: Optional[StrictStr] = Field(default=None, alias="salesRep1")
    lender: Optional[Lender] = None
    product_package: Optional[StrictStr] = Field(default=None, alias="productPackage")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "marketSegment", "saleID", "totalSqft", "totalStairs", "glueDownOrder", "additionalSaleComments", "soldPrice", "paymentType", "inventoryAvailable", "listPrice", "loanAmount", "buydown", "repSplit", "salesRep1", "lender", "productPackage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SoldOrder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of lender
        if self.lender:
            _dict['lender'] = self.lender.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SoldOrder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "marketSegment": obj.get("marketSegment"),
            "saleID": obj.get("saleID"),
            "totalSqft": obj.get("totalSqft"),
            "totalStairs": obj.get("totalStairs"),
            "glueDownOrder": obj.get("glueDownOrder"),
            "additionalSaleComments": obj.get("additionalSaleComments"),
            "soldPrice": obj.get("soldPrice"),
            "paymentType": obj.get("paymentType"),
            "inventoryAvailable": obj.get("inventoryAvailable"),
            "listPrice": obj.get("listPrice"),
            "loanAmount": obj.get("loanAmount"),
            "buydown": obj.get("buydown"),
            "repSplit": obj.get("repSplit"),
            "salesRep1": obj.get("salesRep1"),
            "lender": Lender.from_dict(obj["lender"]) if obj.get("lender") is not None else None,
            "productPackage": obj.get("productPackage")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


