# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Unavailable(BaseModel):
    """
    Unavailable
    """ # noqa: E501
    id: Optional[StrictStr] = None
    comments: Optional[StrictStr] = None
    assigned_to_name: Optional[StrictStr] = Field(default=None, alias="assignedToName")
    assigned_to_phone: Optional[StrictStr] = Field(default=None, alias="assignedToPhone")
    name: Optional[StrictStr] = None
    assigned_to_email: Optional[StrictStr] = Field(default=None, alias="assignedToEmail")
    activity_type: Optional[StrictStr] = Field(default=None, alias="activityType")
    assigned_to: Optional[StrictStr] = Field(default=None, alias="assignedTo")
    market_segment: Optional[StrictStr] = Field(default=None, alias="marketSegment")
    end_date: Optional[datetime] = Field(default=None, alias="endDate")
    start_date: Optional[datetime] = Field(default=None, alias="startDate")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "comments", "assignedToName", "assignedToPhone", "name", "assignedToEmail", "activityType", "assignedTo", "marketSegment", "endDate", "startDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Unavailable from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Unavailable from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "comments": obj.get("comments"),
            "assignedToName": obj.get("assignedToName"),
            "assignedToPhone": obj.get("assignedToPhone"),
            "name": obj.get("name"),
            "assignedToEmail": obj.get("assignedToEmail"),
            "activityType": obj.get("activityType"),
            "assignedTo": obj.get("assignedTo"),
            "marketSegment": obj.get("marketSegment"),
            "endDate": obj.get("endDate"),
            "startDate": obj.get("startDate")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


