"""
    services API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from fusion_refloor.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from fusion_refloor.exceptions import ApiAttributeError



class Crew(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'id': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'active': (str,),  # noqa: E501
            'email': (str,),  # noqa: E501
            'city': (str,),  # noqa: E501
            'company_name': (str,),  # noqa: E501
            'market_segment': (str,),  # noqa: E501
            'mobile_phone': (str,),  # noqa: E501
            'street_address1': (str,),  # noqa: E501
            'state_province': (str,),  # noqa: E501
            'sqft_per_day': (int,),  # noqa: E501
            'sqft_per_week': (int,),  # noqa: E501
            'works_saturday': (bool,),  # noqa: E501
            'total_completed_installs': (int,),  # noqa: E501
            'total_be_backs': (int,),  # noqa: E501
            'percent_of_be_backs_to_installs': (float,),  # noqa: E501
            'move_appliances': (bool,),  # noqa: E501
            'rip_and_haul': (bool,),  # noqa: E501
            'stairs': (bool,),  # noqa: E501
            'leveling': (bool,),  # noqa: E501
            'position_title': (str,),  # noqa: E501
            'glue_down_installation': (bool,),  # noqa: E501
            'date_certified': (date,),  # noqa: E501
            'project_capabilities': (str,),  # noqa: E501
            'plywood_and_subfloor_replacement': (bool,),  # noqa: E501
            'baseboard_installation': (bool,),  # noqa: E501
            'star_rating': (float,),  # noqa: E501
            'attendance_violations': (int,),  # noqa: E501
            'stairs_per_day': (int,),  # noqa: E501
            'leveling_sqft': (int,),  # noqa: E501
            'grade': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'name': 'name',  # noqa: E501
        'active': 'active',  # noqa: E501
        'email': 'email',  # noqa: E501
        'city': 'city',  # noqa: E501
        'company_name': 'companyName',  # noqa: E501
        'market_segment': 'marketSegment',  # noqa: E501
        'mobile_phone': 'mobilePhone',  # noqa: E501
        'street_address1': 'streetAddress1',  # noqa: E501
        'state_province': 'stateProvince',  # noqa: E501
        'sqft_per_day': 'sqftPerDay',  # noqa: E501
        'sqft_per_week': 'sqftPerWeek',  # noqa: E501
        'works_saturday': 'worksSaturday',  # noqa: E501
        'total_completed_installs': 'totalCompletedInstalls',  # noqa: E501
        'total_be_backs': 'totalBeBacks',  # noqa: E501
        'percent_of_be_backs_to_installs': 'percentOfBeBacksToInstalls',  # noqa: E501
        'move_appliances': 'moveAppliances',  # noqa: E501
        'rip_and_haul': 'ripAndHaul',  # noqa: E501
        'stairs': 'stairs',  # noqa: E501
        'leveling': 'leveling',  # noqa: E501
        'position_title': 'positionTitle',  # noqa: E501
        'glue_down_installation': 'glueDownInstallation',  # noqa: E501
        'date_certified': 'dateCertified',  # noqa: E501
        'project_capabilities': 'projectCapabilities',  # noqa: E501
        'plywood_and_subfloor_replacement': 'plywoodAndSubfloorReplacement',  # noqa: E501
        'baseboard_installation': 'baseboardInstallation',  # noqa: E501
        'star_rating': 'starRating',  # noqa: E501
        'attendance_violations': 'attendanceViolations',  # noqa: E501
        'stairs_per_day': 'stairsPerDay',  # noqa: E501
        'leveling_sqft': 'levelingSqft',  # noqa: E501
        'grade': 'grade',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Crew - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            active (str): [optional]  # noqa: E501
            email (str): [optional]  # noqa: E501
            city (str): [optional]  # noqa: E501
            company_name (str): [optional]  # noqa: E501
            market_segment (str): [optional]  # noqa: E501
            mobile_phone (str): [optional]  # noqa: E501
            street_address1 (str): [optional]  # noqa: E501
            state_province (str): [optional]  # noqa: E501
            sqft_per_day (int): [optional]  # noqa: E501
            sqft_per_week (int): [optional]  # noqa: E501
            works_saturday (bool): [optional]  # noqa: E501
            total_completed_installs (int): [optional]  # noqa: E501
            total_be_backs (int): [optional]  # noqa: E501
            percent_of_be_backs_to_installs (float): [optional]  # noqa: E501
            move_appliances (bool): [optional]  # noqa: E501
            rip_and_haul (bool): [optional]  # noqa: E501
            stairs (bool): [optional]  # noqa: E501
            leveling (bool): [optional]  # noqa: E501
            position_title (str): [optional]  # noqa: E501
            glue_down_installation (bool): [optional]  # noqa: E501
            date_certified (date): [optional]  # noqa: E501
            project_capabilities (str): [optional]  # noqa: E501
            plywood_and_subfloor_replacement (bool): [optional]  # noqa: E501
            baseboard_installation (bool): [optional]  # noqa: E501
            star_rating (float): [optional]  # noqa: E501
            attendance_violations (int): [optional]  # noqa: E501
            stairs_per_day (int): [optional]  # noqa: E501
            leveling_sqft (int): [optional]  # noqa: E501
            grade (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Crew - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            active (str): [optional]  # noqa: E501
            email (str): [optional]  # noqa: E501
            city (str): [optional]  # noqa: E501
            company_name (str): [optional]  # noqa: E501
            market_segment (str): [optional]  # noqa: E501
            mobile_phone (str): [optional]  # noqa: E501
            street_address1 (str): [optional]  # noqa: E501
            state_province (str): [optional]  # noqa: E501
            sqft_per_day (int): [optional]  # noqa: E501
            sqft_per_week (int): [optional]  # noqa: E501
            works_saturday (bool): [optional]  # noqa: E501
            total_completed_installs (int): [optional]  # noqa: E501
            total_be_backs (int): [optional]  # noqa: E501
            percent_of_be_backs_to_installs (float): [optional]  # noqa: E501
            move_appliances (bool): [optional]  # noqa: E501
            rip_and_haul (bool): [optional]  # noqa: E501
            stairs (bool): [optional]  # noqa: E501
            leveling (bool): [optional]  # noqa: E501
            position_title (str): [optional]  # noqa: E501
            glue_down_installation (bool): [optional]  # noqa: E501
            date_certified (date): [optional]  # noqa: E501
            project_capabilities (str): [optional]  # noqa: E501
            plywood_and_subfloor_replacement (bool): [optional]  # noqa: E501
            baseboard_installation (bool): [optional]  # noqa: E501
            star_rating (float): [optional]  # noqa: E501
            attendance_violations (int): [optional]  # noqa: E501
            stairs_per_day (int): [optional]  # noqa: E501
            leveling_sqft (int): [optional]  # noqa: E501
            grade (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
