# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fusion_refloor.models.commission_request import CommissionRequest

class TestCommissionRequest(unittest.TestCase):
    """CommissionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommissionRequest:
        """Test CommissionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommissionRequest`
        """
        model = CommissionRequest()
        if include_optional:
            return CommissionRequest(
                sale_id = '',
                product_package = '',
                sold_price = 1.337,
                list_price = 1.337,
                lender_fees = 1.337,
                loan_amount = 1.337,
                below_list_percent = 1.337,
                lender = fusion_refloor.models.lender.Lender(
                    id = '', 
                    name = '', ),
                rep_split = 1.337,
                non_commissionable_total = 1.337
            )
        else:
            return CommissionRequest(
        )
        """

    def testCommissionRequest(self):
        """Test CommissionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
