# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fusion_refloor.models.schedule_model import ScheduleModel

class TestScheduleModel(unittest.TestCase):
    """ScheduleModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleModel:
        """Test ScheduleModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleModel`
        """
        model = ScheduleModel()
        if include_optional:
            return ScheduleModel(
                order = fusion_refloor.models.order.Order(
                    id = '', 
                    market_segment = '', 
                    sale_id = '', 
                    total_sqft = 56, 
                    total_stairs = 56, 
                    glue_down_order = True, 
                    additional_sale_comments = '', 
                    sold_price = 1.337, 
                    payment_type = '', 
                    inventory_available = True, ),
                sale_order_items = [
                    fusion_refloor.models.order_item.OrderItem(
                        id = '', 
                        appliance_count = 56, 
                        move_piano_pool_table = '', 
                        multiple_layers = 56, 
                        open_stair_count = 56, 
                        patch_leveling_required = True, 
                        pedestal_sink_rr = True, 
                        plywood_half_inch_sheets = 56, 
                        plywood_quarter_inch_sheets = 56, 
                        plywood_three_quarter_inch_sheets = 56, 
                        primer_type = '', 
                        room_sq_ft = 56, 
                        stair_count = 56, 
                        toilet_rr = True, 
                        true_self_leveling_required = True, 
                        vapor_barrier = 1.337, 
                        sale = '', 
                        bifold_door_count = 56, 
                        build_up_leveling_required = 56, 
                        product_selected = '', 
                        bcid = '', 
                        molding_type = '', 
                        current_covering_type = '', 
                        remove_current_surface = True, 
                        available = True, 
                        product_name = '', 
                        product_grade = '', 
                        non_commissionable_item_total = 1.337, )
                    ],
                inventory_items = [
                    fusion_refloor.models.inventory_item.InventoryItem(
                        id = '', 
                        no = '', 
                        location_name = '', 
                        sqft_per_case = 1.337, 
                        description = '', 
                        item_category_code = '', 
                        qoh = 1.337, 
                        location_code = '', 
                        linear_ft_per_unit = 1.337, )
                    ],
                purchase_order_items = [
                    fusion_refloor.models.purchase_order_item.PurchaseOrderItem(
                        id = '', 
                        no = '', 
                        qpo = 56, 
                        location_name = '', 
                        sqft_per_case = 1.337, 
                        description = '', 
                        item_category_code = '', 
                        location_code = '', 
                        linear_ft_per_unit = 1.337, )
                    ],
                flooring_colors = [
                    fusion_refloor.models.flooring_color.FlooringColor(
                        name = '', 
                        product_lines = '', 
                        thumbnail = '', 
                        color_upcharge = 1.337, 
                        sales_app_display_name = '', 
                        in_stock = True, 
                        glue_down = True, )
                    ],
                crews = [
                    fusion_refloor.models.crew.Crew(
                        id = '', 
                        name = '', 
                        active = '', 
                        email = '', 
                        city = '', 
                        company_name = '', 
                        market_segment = '', 
                        mobile_phone = '', 
                        street_address1 = '', 
                        state_province = '', 
                        sqft_per_day = 56, 
                        sqft_per_week = 56, 
                        works_saturday = True, 
                        total_completed_installs = 56, 
                        total_be_backs = 56, 
                        percent_of_be_backs_to_installs = 1.337, 
                        move_appliances = True, 
                        rip_and_haul = True, 
                        stairs = True, 
                        leveling = True, 
                        position_title = '', 
                        glue_down_installation = True, 
                        date_certified = 'Thu Mar 10 00:00:00 UTC 2022', 
                        project_capabilities = '', 
                        plywood_and_subfloor_replacement = True, 
                        baseboard_installation = True, 
                        star_rating = 1.337, 
                        attendance_violations = 56, 
                        stairs_per_day = 56, 
                        leveling_sqft = 56, 
                        grade = '', )
                    ],
                unavailability = [
                    fusion_refloor.models.unavailable.Unavailable(
                        id = '', 
                        comments = '', 
                        assigned_to_name = '', 
                        assigned_to_phone = '', 
                        name = '', 
                        assigned_to_email = '', 
                        activity_type = '', 
                        assigned_to = '', 
                        market_segment = '', 
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                inventory_available = True,
                color_not_in_stock = True,
                glue_down_order = True,
                total_stairs = 56
            )
        else:
            return ScheduleModel(
        )
        """

    def testScheduleModel(self):
        """Test ScheduleModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
