# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fusion_refloor.api.scheduling_services_api import SchedulingServicesApi


class TestSchedulingServicesApi(unittest.TestCase):
    """SchedulingServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SchedulingServicesApi()

    def tearDown(self) -> None:
        pass

    def test_schedule_existing_order(self) -> None:
        """Test case for schedule_existing_order

        Schedule crews using existing order
        """
        pass

    def test_schedule_new_order(self) -> None:
        """Test case for schedule_new_order

        Schedule crews using populated order
        """
        pass

    def test_schedule_resource_get_order(self) -> None:
        """Test case for schedule_resource_get_order

        Get an existing order
        """
        pass


if __name__ == '__main__':
    unittest.main()
