# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fusion_refloor.models.unavailable import Unavailable

class TestUnavailable(unittest.TestCase):
    """Unavailable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Unavailable:
        """Test Unavailable
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Unavailable`
        """
        model = Unavailable()
        if include_optional:
            return Unavailable(
                id = '',
                comments = '',
                assigned_to_name = '',
                assigned_to_phone = '',
                name = '',
                assigned_to_email = '',
                activity_type = '',
                assigned_to = '',
                market_segment = '',
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Unavailable(
        )
        """

    def testUnavailable(self):
        """Test Unavailable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
