# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fusion_refloor.models.proposed_crew import ProposedCrew

class TestProposedCrew(unittest.TestCase):
    """ProposedCrew unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProposedCrew:
        """Test ProposedCrew
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProposedCrew`
        """
        model = ProposedCrew()
        if include_optional:
            return ProposedCrew(
                id = '',
                name = '',
                active = '',
                email = '',
                city = '',
                company_name = '',
                market_segment = '',
                mobile_phone = '',
                street_address1 = '',
                state_province = '',
                sqft_per_day = 56,
                sqft_per_week = 56,
                works_saturday = True,
                total_completed_installs = 56,
                total_be_backs = 56,
                percent_of_be_backs_to_installs = 1.337,
                move_appliances = True,
                rip_and_haul = True,
                stairs = True,
                leveling = True,
                position_title = '',
                glue_down_installation = True,
                date_certified = 'Thu Mar 10 00:00:00 UTC 2022',
                project_capabilities = '',
                plywood_and_subfloor_replacement = True,
                baseboard_installation = True,
                star_rating = 1.337,
                attendance_violations = 56,
                stairs_per_day = 56,
                leveling_sqft = 56,
                grade = '',
                slot = fusion_refloor.models.proposed_slot.ProposedSlot(
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return ProposedCrew(
        )
        """

    def testProposedCrew(self):
        """Test ProposedCrew"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
