# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fusion_refloor.models.sold_order import SoldOrder

class TestSoldOrder(unittest.TestCase):
    """SoldOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SoldOrder:
        """Test SoldOrder
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SoldOrder`
        """
        model = SoldOrder()
        if include_optional:
            return SoldOrder(
                id = '',
                market_segment = '',
                sale_id = '',
                total_sqft = 56,
                total_stairs = 56,
                glue_down_order = True,
                additional_sale_comments = '',
                sold_price = 1.337,
                payment_type = '',
                inventory_available = True,
                list_price = 1.337,
                loan_amount = 1.337,
                buydown = 1.337,
                rep_split = 1.337,
                sales_rep1 = '',
                lender = fusion_refloor.models.lender.Lender(
                    id = '', 
                    name = '', ),
                product_package = ''
            )
        else:
            return SoldOrder(
        )
        """

    def testSoldOrder(self):
        """Test SoldOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
