# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fusion_refloor.models.inventory_item import InventoryItem

class TestInventoryItem(unittest.TestCase):
    """InventoryItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InventoryItem:
        """Test InventoryItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InventoryItem`
        """
        model = InventoryItem()
        if include_optional:
            return InventoryItem(
                id = '',
                no = '',
                location_name = '',
                sqft_per_case = 1.337,
                description = '',
                item_category_code = '',
                qoh = 1.337,
                location_code = '',
                linear_ft_per_unit = 1.337
            )
        else:
            return InventoryItem(
        )
        """

    def testInventoryItem(self):
        """Test InventoryItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
