# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fusion_refloor.models.flooring_color import FlooringColor

class TestFlooringColor(unittest.TestCase):
    """FlooringColor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlooringColor:
        """Test FlooringColor
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlooringColor`
        """
        model = FlooringColor()
        if include_optional:
            return FlooringColor(
                name = '',
                product_lines = '',
                thumbnail = '',
                color_upcharge = 1.337,
                sales_app_display_name = '',
                in_stock = True,
                glue_down = True
            )
        else:
            return FlooringColor(
        )
        """

    def testFlooringColor(self):
        """Test FlooringColor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
