# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fusion_refloor.models.order_item import OrderItem

class TestOrderItem(unittest.TestCase):
    """OrderItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderItem:
        """Test OrderItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderItem`
        """
        model = OrderItem()
        if include_optional:
            return OrderItem(
                id = '',
                appliance_count = 56,
                move_piano_pool_table = '',
                multiple_layers = 56,
                open_stair_count = 56,
                patch_leveling_required = True,
                pedestal_sink_rr = True,
                plywood_half_inch_sheets = 56,
                plywood_quarter_inch_sheets = 56,
                plywood_three_quarter_inch_sheets = 56,
                primer_type = '',
                room_sq_ft = 56,
                stair_count = 56,
                toilet_rr = True,
                true_self_leveling_required = True,
                vapor_barrier = 1.337,
                sale = '',
                bifold_door_count = 56,
                build_up_leveling_required = 56,
                product_selected = '',
                bcid = '',
                molding_type = '',
                current_covering_type = '',
                remove_current_surface = True,
                available = True,
                product_name = '',
                product_grade = '',
                non_commissionable_item_total = 1.337
            )
        else:
            return OrderItem(
        )
        """

    def testOrderItem(self):
        """Test OrderItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
