# coding: utf-8

"""
    gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0-SNAPSHOT
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fusion_refloor.api.commissions_services_api import CommissionsServicesApi


class TestCommissionsServicesApi(unittest.TestCase):
    """CommissionsServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommissionsServicesApi()

    def tearDown(self) -> None:
        pass

    def test_commission_resource_calculate(self) -> None:
        """Test case for commission_resource_calculate

        Calculate commision
        """
        pass

    def test_commission_resource_get_commission(self) -> None:
        """Test case for commission_resource_get_commission

        Get commission
        """
        pass

    def test_commission_resource_get_commission_order(self) -> None:
        """Test case for commission_resource_get_commission_order

        Get commission
        """
        pass


if __name__ == '__main__':
    unittest.main()
