# -*- coding: utf-8 -*-
{
    'name': 'Sale Contract',
    'version': '1.1',
    'category': 'Sales/Sales',
    'author': 'Sagar Mokariya',
    'website': 'https://www.xeonglobal.com',
    'summary': 'Sale Contract Creation & Configurations',
    'description': """
This module customizing sale module to create a sale contract & followups.
    """,
    'depends': ['sale', 'sale_management', 'base_geolocalize','otl_document_sign', 'payment_bancard', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'security/user_security.xml',
        'data/ir_actions_server.xml',
        'data/appointment_sequence_data.xml',
        'data/payment_data.xml',
        'data/cron_data.xml',
        'data/master_configuration_data.xml',
        'data/sale_data.xml',
        'data/email_template_data.xml',
        'views/master_configuration_views.xml',
        'views/quote_question_views.xml',
        'views/team_customer_appointment_view.xml',
        'views/sale_contract_views.xml',
        'views/sale_order_contract_views.xml',
        'views/team_floor_molding_views.xml',
        'views/team_contract_question_line_views.xml',
        'views/team_contract_room_measurement_line_views.xml',
        'views/team_credit_application_views.xml',
        'views/appointment_result_views.xml',
        'views/otl_api_sync_log_view.xml',
        'views/otl_appointment_sync_log_views.xml',
        'views/i360_users_views.xml',
        
        'views/res_config_settings_views.xml',
        'wizard/generate_token_wizard_view.xml',
        'wizard/day_wise_report_wizrd_view.xml',
    ],
    
    'installable': True,
    'auto_install': False,
    'license': 'OPL-1',
}
